### ISSUE TITLE
応募画面のバックエンド実装

### ISSUE THREAD

**Issue by DaisukeKurita** [mysthkr/medi_app#2]
## バリデーションの設定
- [x] 未入力をはじく
- [x] メールアドレスの正規表現を設定
- [x] 電話番号の正規表現・一意性を設定（ハイフンなし、携帯電話番号として設定）
- [x]  パスワードの文字数制限・一意性を設定

## 国際化
- [x] 国際化
- [x] tailwindcss-railsの設定

## データベースの設定
- [x] config/database.ymlを、.gitignoreに追加

**Comment by mysthkr** [comment]
バリデーションの設定だけ実装したら、フロント開発に着手いただけると幸いです。。。
